### ISSUE TITLE
await process.death unerwartetes verhalten

### ISSUE THREAD

**Issue by donjuandem** [CircleOfNice/CoreWorker#22]
### Problem
Process, der als stream instanziiert wurde, schmiert beim await death mit exit code 1 ab:

Code:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 11 05" src="https://cloud.githubusercontent.com/assets/1221906/11810311/583c4334-a32d-11e5-91b7-27eb0eab35a1.png">

Output:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 11 38" src="https://cloud.githubusercontent.com/assets/1221906/11810317/645c06ae-a32d-11e5-8191-048bc7bd074f.png">

### Lösung
Den prozess nach dem await death von hand killen (ganz komische sache :D)

Code:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 13 38" src="https://cloud.githubusercontent.com/assets/1221906/11810355/ab7cf93a-a32d-11e5-9c58-d4eb4fd3908b.png">

Output:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 13 16" src="https://cloud.githubusercontent.com/assets/1221906/11810350/a38c9da2-a32d-11e5-8399-ee3c57a076b3.png">

Ich vermute, dass das iwie durch die art deines kills bei dem await getriggert wird. vermutlich muss man da stufenweise dann vorgehen oder so

**Comment by ansgarS** [comment]
Ich versuche das gerade zu verstehen :D
Fall 1: Du killst den Prozess nicht von Hand. Er beendet sich von irgendwann selbst und returned aber nen Exit Code !== 0

Fall 2: Du killst den Prozess von Hand mit process.kill. Er beendet sich mit einem Signal und deswegen schmeißt er auch keinen Error?

Bist du denn sicher, dass der Prozess auch ohne kill sich normal beendet?

**Comment by donjuandem** [comment]
der prozess is wien server der beendet sich eigtl erstmal gar nich selbs. Deswgeen war ich ja verwundert, dass anscheinend son kill von death getriggered wird (was je nachdem ja auch gar nich so uninteressant wäre, genau für den use case), aber wunderte mich, dass der mit nem error beendet. Vermutlich is es jetz so, dass der gar keinen kill intern triggert, sondern der timeout von dem test zuschlägt, den test killed und dadurch der error code entsteht.

Folgende idee: death ohne timeout triggert den kill und returned sobald das erfolgreich war? gibts szenarien wo das probleme macht?

**Comment by ansgarS** [comment]
Zunächst einmal müssen wir gucken, warum death den kill da triggert...
Da scheint ja irgendwas nicht zu stimmen. Vllt. liegt das auch am Stream, dass der nix rein bekommt, und sich deswegen iwie schließt.

Kannst du das irgendwie in deinem Programm mal evaluieren?

Nebenher kann ich natürlich schonmal gucken, ob das großartige Änderungen mit sich zieht, wenn death ohne timeout wie ein async kill gehandelt wird.

**Comment by ansgarS** [comment]
Das wäre sogar ganz praktisch, da es ja Prozesse gibt, die sich nicht so ohne weiteres killen lassen. Sodass man dann von Hand 
```js
process(`kill -9 ${stupidProcessThatdoesntWantToClose.pid}`).death(300);
``` 
im schlimmsten fall callen kann

**Comment by donjuandem** [comment]
>  Zunächst einmal müssen wir gucken, warum death den kill da triggert...
> Vermutlich is es jetz so, dass der gar keinen kill intern triggert, sondern der timeout von dem test zuschlägt, den test killed und dadurch der error code entsteht.

is shcon beantwortet gewesen

**Comment by ansgarS** [comment]
Oh hopppla :D 
Ja muss so sein. Habe gerade ein Besipiel aufgezogen ^^
![image](https://cloud.githubusercontent.com/assets/7502582/11871081/410fbfc8-a4cd-11e5-8a92-f00c3cc51a13.png)

**Comment by donjuandem** [comment]
ja, sieht gut aus grundsätzlich

**Comment by ansgarS** [comment]
Aber tatsächlich ist das in dem Stream gar nicht so leicht:
Wenn ich während des Stream den process killen möchte, gibts fiese errors:
```js
fs.createReadStream("package.json").pipe(stream).pipe(logger);

setTimeout(function() {
    inputLogger.kill();
}, 0);
```
führt zu 
```console
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

**Comment by donjuandem** [comment]
der muss, bevor du den prozess killst, im stream nen "end" event emitten, damit erst der stream beendet wird (also kein datenfluss mehr stattfindet) und dann die dest des streams beendet wird

**Comment by ansgarS** [comment]
Okay also dann folgendes Vorgehen:
1. .death() ohne timeout triggert kill
2. solange der stream jedoch nicht beendet ist, kann er noch nicht killen
3. sobald der process gekilled is resolved death

**Comment by ansgarS** [comment]
Ne moment, das is käse :D Wenn der stream beendet ist, schließt sich der prozess ja sowieso

**Comment by ansgarS** [comment]
Was geht, und den Prozess anschließend auch beendet, wäre 
stream.pause();

**Comment by ansgarS** [comment]
Folgendes habe ich jetzt getestet:
1. Ersteinmal habe ich die `end() {}` aus dem duplexstream entfernt und in den constructor `this.on("end", ::this.instance.end);`
2. Wenn ich jetzt vorzeitig `stream.end()` calle, dann fliegt mir zwar das ding nicht mehr um die Ohren, aber death rejected mit `DeathError [SyntaxError: Unexpected end of input]`

Is ja auch nicht sinn und Zweck... Rein Theoretisch muss ja der Readstream vor dem DuplexStream beendet werden, um das clean hinzubekommen... Da hat man aber halt keinen Zugriff im Duplex drauf...
Das klingt auf jeden fall nach einer problematische Kiste...

**Comment by donjuandem** [comment]
hasde mal probiert end zu emitten, so dass der stream die chance hat, sich selber zu beenden? (bin da auch unsicher). Spricht ansonsten was gegen pause?

**Comment by ansgarS** [comment]
Wenn ich die Stream richtig verstanden habe, wird bei end in jedem nächsten Stream "end" emitted.

Ja ich mach das dann mit pause:

death() --> runningStream  ? stream.pause() : process.kill();

**Comment by donjuandem** [comment]
gut
