### ISSUE TITLE
pipe funktioniert nich richtig

### ISSUE THREAD

**Issue by donjuandem** [CircleOfNice/CoreWorker#23]
Code:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 22 16" src="https://cloud.githubusercontent.com/assets/1221906/11810522/05d50ef8-a32f-11e5-9464-cef43edac92d.png">

Output:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 21 46" src="https://cloud.githubusercontent.com/assets/1221906/11810526/0eef4f26-a32f-11e5-96ad-b0c16a49cdd2.png">

Problemstelle:
<img width="1280" alt="bildschirmfoto 2015-12-15 um 13 21 53" src="https://cloud.githubusercontent.com/assets/1221906/11810579/73a2a2ec-a32f-11e5-9f05-cfb76448bc39.png">

Lösung:
Also warum stream.write nich da is, kann ich nich sagen, aber normalerweise sollte dieser duplexstream transform oder so erweitern und nich nur writable

**Comment by ansgarS** [comment]
Hmm auch hier bin ich mir so gar nicht sicher :D 

Fall 1 Transformstream
wir haben transform(chunk, enc, next):
--> sobald next gecallt wird, gehts weiter in den nächsten stream
--> also muss immer wenn was in transform reinkommt, die funktion so lange warten bis wieder was aus process.stdout/stderr kommt, um das weitergeben zu können
--> klingt also iwie falsch

Fall 2 DuplexStream
wir erweitern also um eine read(n)
--> da bin ich mir nicht sicher, wie das funktionieren soll, weil die doku bei den stream so unglaublich schlecht ist
vllt. geht das so:
```js
constructor() {
    this.emitter.on("data", this.read);
}

read(chunk) {
   this.push(chunk);
}
```
doch soll ja read als parameter die bytegröße oder so bekommen :confused:

**Comment by ansgarS** [comment]
Oder folgendes vielleicht:
```js
pipe(writable stream) {
  instance.process.stdout.pipe(writable stream);
  instance.proces.stderr.pipe(writable stream);
}

**Comment by donjuandem** [comment]
nein kein eigenes pipe das is mist, pipe implementiert der readstream, daher brauchen wir auf jeden fall einen duplex oder transform, da ich von außen doch auch in den stdin von dem prozess schreiben können will. das heißt:

im constructor von dem duplexding mussde im constructor sagen `this.instance.emitter.on("data", ::this.push);` und bei dem _transform nur 

```js
transform(data, enc, cb) {
   this.instance.stdin.write(data);
   cb();
}
```

**Comment by donjuandem** [comment]
zur erklärung: diese streams haben immer einen outputbuffer (außer natürlich reine writable denke ich) und das pipe läuft so, wenn wir folgendes hätten `a.pipe(b)`: b fragt die ganze zeit a: has du wat neues. und a guckt dann: hab ich was auf dem outputbuffer, wenn ja gib das nächste element nach fifo raus, ansonsten weiß b dass nix neues da is.

**Comment by ansgarS** [comment]
Also wäre das wie folgt: 
```js
class myownduplexstream extends Transform {
    constructor(emitter) {
        emitter.on("data", this.push);
    }

    transform(data, enc, cb) {
        this.instance.stdin.write(data);
        cb();
    }
}
```

**Comment by donjuandem** [comment]
ja im grunde, nur mir _transform und ::this.push und analog zu dem aktuellen code instance.emitter.on

**Comment by ansgarS** [comment]
So habe es mit folgenden Beispiel getestet (sodass es auch ab sofort in meiner Development-Db liegt :D):
```js
"use strict";

var Transform = require("stream").Transform;
var Emitter   = require("events").EventEmitter;
var Writable  = require("stream").Writable;

var intervalWriter = new Emitter();
var logger         = new Writable();
var counter        = 0;

logger._write = function(chunk, enc, next) {
    console.log("Logger", chunk.toString());
    next();
};

class SomeDuplex extends Transform {
    constructor() {
        super();

        intervalWriter.on("data", this.push.bind(this));
    }

    _transform(chunk, enc, next) {
        console.log("Got a chunk", chunk.toString());
        next();
    }
}

var myDuplex = new SomeDuplex();

myDuplex.pipe(logger);

setInterval(function() {
    counter = counter + 1;
    intervalWriter.emit("data", "Hello Ansgar\n");
    if(counter % 5 === 0) myDuplex.write("Nonono");
}, 100);
```

und der Output:
```console
Logger Hello Ansgar
Logger Hello Ansgar
Logger Hello Ansgar
Logger Hello Ansgar
Logger Hello Ansgar
Got a chunk Nonono
```
